# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pandas-1.0.0-python_3.7-on-linux_64, last modified Wed Jan 29 23:06:02 2020
# ------------------------------------------------

package:
    name: pandas
    version: 1.0.0
source:
    sha256: 3ea6cc86931f57f18b1240572216f09922d91b19ab8a01cf24734394a3db3bec
    url: https://github.com/pandas-dev/pandas/releases/download/v1.0.0/pandas-1.0.0.tar.gz
build:
    number: '0'
    script: /tmp/build/80754af9/pandas_1580339294458/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        -m pip install --no-deps --ignore-installed .
    string: py37h0573a6f_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - blas 1.0 mkl
        - ca-certificates 2019.11.27 0
        - certifi 2019.11.28 py37_0
        - cython 0.29.14 py37he6710b0_0
        - intel-openmp 2019.4 243
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - mkl 2019.4 243
        - mkl-service 2.3.0 py37he904b0f_0
        - mkl_fft 1.0.15 py37ha843d7b_0
        - mkl_random 1.1.0 py37hd6b4f25_0
        - ncurses 6.1 he6710b0_1
        - numpy 1.14.6 py37h3b04361_5
        - numpy-base 1.14.6 py37hde5b4d6_5
        - openssl 1.1.1d h7b6447c_3
        - pip 20.0.2 py37_0
        - python 3.7.6 h0371630_2
        - readline 7.0 h7b6447c_5
        - setuptools 45.1.0 py37_0
        - six 1.14.0 py37_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.6 py37_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - numpy >=1.14.6,<2.0a0
        - python >=3.7,<3.8.0a0
        - python-dateutil >=2.6.1
        - pytz >=2017.2
test:
    imports:
        - pandas
about:
    home: http://pandas.pydata.org
    license: BSD 3-clause
    license_file: LICENSE
    summary: High-performance, easy-to-use data structures and data analysis tools.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - TomAugspurger
        - WillAyd
        - jorisvandenbossche
        - jreback
        - msarahan
        - ocefpaf
